AbdulazizovBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('main.urls', namespace='main')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    prefix_default_language=False,
)



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

# handler404 = 'main.views.error_404_view'

main/urls.py
from django.urls import path,include
from .import views
from django.utils.translation import gettext as _

app_name = 'main'

urlpatterns = [
	# path('',views.HomePageView.as_view(), name='home'),
	path('',views.home, name='home'),
	path('about/',views.about, name='about'),
	path('post/<slug:post_slug>', views.postDetailView, name='post_detail'),
	path('test/', views.test, name='test'),


	# path('about/',views.AboutPageView.as_view(), name='about'),
	# path('category/<pk>', views.CategoryDetailView.as_view(), name='category_detail'),
	# path('product/<pk>', views.ProductDetailView.as_view(), name='product_detail'),
	
	# path('category_delete/<pk>', views.category_delete, name='category_delete'),
	# path('product_delete/<pk>', views.product_delete, name='product_delete'),
	# path('error/', views.ErrorPageView.as_view(), name='error'),
]

templates/Trash/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Django Easy Pjax test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">

</head>
<body>
<!-- <nav class="navbar navbar-default" role="navigation"> -->
    <!-- <div class="container"> -->
            <!-- <a class="navbar-brand" href="{% url 'main:home' %}">easy-pjax</a> -->
            <!-- <ul class="nav navbar-nav">
                <li><a href="{% url 'main:about' %}"><span class="glyphicon glyphicon-star"></span> Page 1</a></li>
                <li><a href="{% url 'main:test' %}"><span class="glyphicon glyphicon-fire"></span> Page 2</a></li>
            </ul> -->
            <!-- <p class="checkbox navbar-text" data-toggle="tooltip" data-placement="bottom" title="Turn PJAX loading on/off"> -->
                <!-- <label> -->
                    <input type="checkbox" checked="checked" hidden> 
                <!-- </label> -->
            <!-- </p> -->
            <p class="navbar-text hidden" id="loading"><span class="glyphicon glyphicon-refresh"></span> Loading..</p>
    <!-- </div> -->
<!-- </nav> -->














        <div class="col-sm-12" id="pjax-container">
            {% block content %}
            {% endblock %}
        </div>






















        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script type="text/javascript" src="//code.jquery.com/jquery.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.min.js"></script>
<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'jquery.pjax.js' %}"></script>
<script type="text/javascript" src="{% static 'script.js' %}"></script>
</body>
</html>

templates/Trash/index.html
{% extends "base.html"|pjax:request %}

{% block title %}{{ page_name }}{% endblock %}

{% block content %}


    
    {% for p in posts %}
        <a href="{% url 'main:post_detail' p.slug %}"> {{p.slug}} {{p.title}} </a> <br>
    {% endfor %}
        


    <h1>{{ page_name }}</h1>
{% endblock %}

templates/Trash/indexs.html
<!-- <!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="robots" content="noindex, nofollow">
  <title>Custom toolbar</title>
  <script src="https://cdn.ckeditor.com/4.18.0/standard-all/ckeditor.js"></script>
</head>

<body>
  <textarea cols="80" id="editor1" name="editor1" rows="10" data-sample-short>&lt;p&gt;This is some &lt;strong&gt;sample text&lt;/strong&gt;. You are using &lt;a href=&quot;https://ckeditor.com/&quot;&gt;CKEditor&lt;/a&gt;.&lt;/p&gt;</textarea>
  <script>
    CKEDITOR.replace('editor1', {
      // Define the toolbar groups as it is a more accessible solution.
      toolbarGroups: [{
          "name": "basicstyles",
          "groups": ["basicstyles"]
        },
        {
          "name": "links",
          "groups": ["links"]
        },
        {
          "name": "paragraph",
          "groups": ["list", "blocks"]
        },
        {
          "name": "document",
          "groups": ["mode"]
        },
        {
          "name": "insert",
          "groups": ["insert"]
        },
        {
          "name": "styles",
          "groups": ["styles"]
        },
        {
          "name": "about",
          "groups": ["about"]
        }
      ],
      // Remove the redundant buttons from toolbar groups defined above.
      removeButtons: 'Underline,Strike,Subscript,Superscript,Anchor,Styles,Specialchar,PasteFromWord'
    });
  </script>
</body>

</html> -->

templates/Trash/post_detail.html
{% extends "base.html"|pjax:request %}


{% block content %}

<h4>  Post Detail  </h4>
<h4>  {{post}}  </h4>
<a href="{% url 'main:home' %}"> Home </a>

{% endblock %}